# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Josiah Maharaj
email: josiahmaharaj@outlook.com
description: I like to Code Stuff, Design Things and Edit anything! Websites, Apps, Advertisments?...yup! Send me an email and let's work on something new !
baseurl: "/" 
url: "http://josiahmaharaj.github.io" # the base hostname & protocol for your site
twitter_username: josiah_eli
github_username:  josiahmaharaj

# Build settings
markdown: kramdown

port: 5000