---
title: Josiah Maharaj
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: josiahmaharaj@outlook.com
description: I like to Code Stuff, Design Things and Edit anything! Websites, Apps,
  Advertisments?...yup! Send me an email and let's work on something new!, Trinidad,
  W.I.
baseurl: ''
url: http://josiahmaharaj.com
author: Josiah Maharaj
social:
  name: Josiah Maharaj
  links:
  - https://twitter.com/josiah_eli
  - https://www.facebook.com/josiahmaharaj
  - https://github.com/josiahmaharaj
gems:
- jekyll-seo-tag
- jekyll-feed
- jekyll-sitemap
markdown: kramdown
port: 4000
